services:
  portal:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: ${PORTAL_HOST}
    env_file: .env

    ports:
      - ${PORTAL_PORT}:${PORTAL_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
      - portal-node-modules:/server/node_modules

  mongodb:
    container_name: ${MONGODB_HOST}
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongo-data:/data/db

volumes:
  portal-node-modules:
   name: "portal-node-modules"
  mongo-data:
    name: "mongo-data"
    driver: local
  

