name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build-and-test:
    runs-on: ubutu:latest

    steps:
      - name: checkout branch master
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test

      - name: build docker image
        run: docker-compose build

      - name: log in to docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      
